name: Deploy React app to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # מאפשר גם Run ידני מה-UI

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        # CRA נופל על אזהרות ב-CI. מכבים CI כדי לא להכשיל build על ESLint warnings
        run: |
          echo "CI=false" >> $GITHUB_ENV
          npm run build
        env:
          # חשוב לפריסת GitHub Pages תחת /Neched
          PUBLIC_URL: /Neched

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build   # תיקיית ה-build של CRA

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
