name: Deploy React app to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # מאפשר להריץ ידנית מה-UI

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build
        env:
          CI: false            # חשוב: לא להפוך אזהרות לשגיאות
          PUBLIC_URL: /Neched  # בשביל נכון ל-GitHub Pages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
